//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marikina.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class announcement
    {
        public int announcement_id { get; set; }
        public string announcement_title { get; set; }
        public string announcement_desc { get; set; }
        public string announcement_image_name { get; set; }
        public byte[] announcement_image { get; set; }
        public Nullable<int> announcement_image_size { get; set; }
        public Nullable<System.DateTime> announcement_expiration_datetime { get; set; }
    }
}
