//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marikina.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public int banner_id { get; set; }
        public string banner_image_name { get; set; }
        public byte[] banner_image { get; set; }
        public Nullable<int> banner_image_size { get; set; }
    }
}
