//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marikina.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class logo
    {
        public int logo_id { get; set; }
        public string logo_image_name { get; set; }
        public byte[] logo_image { get; set; }
        public Nullable<int> logo_image_size { get; set; }
    }
}
