//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marikina.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class official
    {
        public int official_id { get; set; }
        public string official_name { get; set; }
        public string official_image_name { get; set; }
        public byte[] official_image { get; set; }
        public Nullable<int> official_image_size { get; set; }
        public string official_desc { get; set; }
        public string official_role { get; set; }
        public string official_barangay { get; set; }
        public string official_contact { get; set; }
    }
}
